package com.fruit.model.mall;

import com.fruit.model.base.BaseAsAftersaleod;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsAftersaleod extends BaseAsAftersaleod<AsAftersaleod> {
	public static final AsAftersaleod dao = new AsAftersaleod();
}
