package com.fruit.model.mall;

import com.fruit.model.base.BaseAsAftersaleodDe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AsAftersaleodDe extends BaseAsAftersaleodDe<AsAftersaleodDe> {
	public static final AsAftersaleodDe dao = new AsAftersaleodDe();
}
