package com.fruit.model.mall;

import com.fruit.model.base.BaseMallCustomerShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerShop extends BaseMallCustomerShop<CustomerShop> {
	public static final CustomerShop dao = new CustomerShop();
}
