package com.fruit.model.mall;

import com.fruit.model.base.BaseCustomerRatedDe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerRatedDe extends BaseCustomerRatedDe<CustomerRatedDe> {
	public static final CustomerRatedDe dao = new CustomerRatedDe();
}
