package com.fruit.model.mall;

import com.fruit.model.base.BaseCustomerGift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerGift extends BaseCustomerGift<CustomerGift> {
	public static final CustomerGift dao = new CustomerGift();
}
