package com.fruit.model.mall;

import com.fruit.model.base.BaseCustomerUpRated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerUpRated extends BaseCustomerUpRated<CustomerUpRated> {
	public static final CustomerUpRated dao = new CustomerUpRated();
}
