package com.fruit.model.mall;

import com.fruit.model.base.BaseMallCustomer;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Customer extends BaseMallCustomer<Customer> {
	public static final Customer dao = new Customer();
}
