package com.fruit.model.mall;

import com.fruit.model.base.BaseMallCustomerSku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerSku extends BaseMallCustomerSku<CustomerSku> {
	public static final CustomerSku dao = new CustomerSku();
}
