package com.fruit.model.mall;

import com.fruit.model.base.BaseMallCustomerAddr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerAddr extends BaseMallCustomerAddr<CustomerAddr> {
	public static final CustomerAddr dao = new CustomerAddr();
}
