package com.fruit.model.mall;

import com.fruit.model.base.BaseCustomerRated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CustomerRated extends BaseCustomerRated<CustomerRated> {
	public static final CustomerRated dao = new CustomerRated();
}
