package com.fruit.model.mall;

import com.fruit.model.base.BaseOdOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOdOrder<Order> {
	public static final Order dao = new Order();
}
