package com.fruit.model.mall;

import com.fruit.model.base.BaseOdOrderAddr;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderAddr extends BaseOdOrderAddr<OrderAddr> {
	public static final OrderAddr dao = new OrderAddr();
}
