package com.fruit.model.mall;

import com.fruit.model.base.BaseOdOrderDe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDe extends BaseOdOrderDe<OrderDe> {
	public static final OrderDe dao = new OrderDe();
}
