package com.fruit.model.mall;

import com.alibaba.druid.util.StringUtils;
import com.fruit.core.model.Condition;
import com.fruit.core.model.Operators;
import com.fruit.model.base.BaseMallSku;
import com.jfinal.plugin.activerecord.Page;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sku extends BaseMallSku<Sku> {
    public static final Sku dao = new Sku();

    public Page<Sku> getPage(int page, int rows, String sku) {
        Set<Condition> conditions = new HashSet<Condition>();
        if (!StringUtils.isEmpty(sku)) {
            conditions.add(new Condition("sku", Operators.EQ, sku));
        }
        return this.getPage(page, rows, conditions);
    }
}
