package com.fruit.model.mall;

import com.fruit.model.base.BaseMallSkuNprice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuNprice extends BaseMallSkuNprice<SkuNprice> {
	public static final SkuNprice dao = new SkuNprice();
}
