package com.fruit.model.mall;

import com.fruit.model.base.BaseMallSkuSprice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuSprice extends BaseMallSkuSprice<SkuSprice> {
	public static final SkuSprice dao = new SkuSprice();
}
