package com.fruit.model.mall;

import com.fruit.model.base.BaseUserRated;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRated extends BaseUserRated<UserRated> {
	public static final UserRated dao = new UserRated();
}
