package com.fruit.model.stock;

import com.fruit.core.model.Condition;
import com.fruit.core.model.Operators;
import com.fruit.model.base.BaseSkStock;
import com.jfinal.plugin.activerecord.Db;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkStock extends BaseSkStock<SkStock> {
    public static final SkStock dao = new SkStock();

    public void add(String sku, long quantity) {
        Set<Condition> conditions = new HashSet<Condition>();
        conditions.add(new Condition("sku", Operators.EQ, sku));
        Long count = getCount(conditions);
        if (count > 0) {
            Db.update("UPDATE sk_stock SET quantity = quantity + ? WHERE sku=?", new Object[]{quantity, sku});
        } else {
            SkStock.dao.clear().set("sku", sku).set("quantity", quantity).save();
        }
    }

    public void subtract(String sku, long quantity) {
        add(sku, 0 - quantity);
    }

    public SkStock findBySku(String sku) {
        return findFirst("SELECT * FROM sk_stock WHERE sku=?", sku);
    }
}
