package com.fruit.model.stock;

import com.fruit.model.base.BaseSkStockLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkStockLog extends BaseSkStockLog<SkStockLog> {
	public static final SkStockLog dao = new SkStockLog();
}
