package com.fruit.model.stock;

import com.alibaba.druid.util.StringUtils;
import com.fruit.core.model.Condition;
import com.fruit.core.model.Operators;
import com.fruit.model.ConsoleSequence;
import com.fruit.model.SysUser;
import com.fruit.model.base.BaseSkuInbound;
import com.jfinal.aop.Before;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.tx.Tx;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuInbound extends BaseSkuInbound<SkuInbound> {
    public static final SkuInbound dao = new SkuInbound();

    public Page<SkuInbound> getPage(int page, int rows, String executor) {
        Set<Condition> conditions = new HashSet<Condition>();
        if (!StringUtils.isEmpty(executor)) {
            conditions.add(new Condition("executor", Operators.EQ, executor));
        }
        return this.getPage(page, rows, conditions);
    }
}
