package com.fruit.model.stock;

import com.alibaba.druid.util.StringUtils;
import com.fruit.core.model.Condition;
import com.fruit.core.model.Operators;
import com.fruit.model.base.BaseSkuInboundDe;
import com.jfinal.plugin.activerecord.Page;

import java.util.HashSet;
import java.util.Set;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuInboundDe extends BaseSkuInboundDe<SkuInboundDe> {
	public static final SkuInboundDe dao = new SkuInboundDe();
}
