package com.fruit.model.stock;

import com.fruit.model.base.BaseSkuOutbound;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuOutbound extends BaseSkuOutbound<SkuOutbound> {
	public static final SkuOutbound dao = new SkuOutbound();
}
