package com.fruit.model.stock;

import com.fruit.model.base.BaseSkuOutboundDe;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SkuOutboundDe extends BaseSkuOutboundDe<SkuOutboundDe> {
	public static final SkuOutboundDe dao = new SkuOutboundDe();
}
