package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerRatedDe<M extends BaseCustomerRatedDe<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setRatedID(Long ratedID) {
		set("ratedID", ratedID);
	}

	public Long getRatedID() {
		return get("ratedID");
	}

	public void setOrderDeID(Long orderDeID) {
		set("orderDeID", orderDeID);
	}

	public Long getOrderDeID() {
		return get("orderDeID");
	}

	public void setSku(String sku) {
		set("sku", sku);
	}

	public String getSku() {
		return get("sku");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

}
