package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMallCustomerAddr<M extends BaseMallCustomerAddr<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}

	public String getCustomer() {
		return get("customer");
	}

	public void setAddr(String addr) {
		set("addr", addr);
	}

	public String getAddr() {
		return get("addr");
	}

	public void setRecipient(String recipient) {
		set("recipient", recipient);
	}

	public String getRecipient() {
		return get("recipient");
	}

	public void setPhone(String phone) {
		set("phone", phone);
	}

	public String getPhone() {
		return get("phone");
	}

}
