package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerGift<M extends BaseCustomerGift<M>> extends BaseModel<M> implements IBean {

    public void setId(Integer id) {
        set("id", id);
    }

    public Integer getId() {
        return get("id");
    }

    public void setCustomer(String customer) {
        set("customer", customer);
    }

    public String getCustomer() {
        return get("customer");
    }

    public void setRelationship(String relationship) {
        set("relationship", relationship);
    }

    public String getRelationship() {
        return get("relationship");
    }

    public void setOrderID(String orderID) {
        set("orderID", orderID);
    }

    public String getOrderID() {
        return get("orderID");
    }

    public void setCustomerName(String customerName) {
        set("customerName", customerName);
    }

    public String getCustomerName() {
        return get("customerName");
    }

    public void setRelationshipName(String relationshipName) {
        set("relationshipName", relationshipName);
    }

    public String getRelationshipName() {
        return get("customerName");
    }

    public void setOdtime(Date odtime) {
        set("odtime", odtime);
    }

    public String getOdtime() {
        return get("odtime");
    }

    public void setGift(Long gift) {
        set("gift", gift);
    }

    public Long getGift() {
        return get("gift");
    }

    public void setQuantity(Long quantity) {
        set("quantity", quantity);
    }

    public Long getQuantity() {
        return get("quantity");
    }

    public void setStatus(String status) {
        set("status", status);
    }

    public String getStatus() {
        return get("status");
    }

}
