package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserRated<M extends BaseUserRated<M>> extends BaseModel<M> implements IBean {

    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return get("id");
    }

    public void setSaler(Long saler) {
        set("saler", saler);
    }

    public Long getSaler() {
        return get("saler");
    }

    public void setRated(String rated) {
        set("rated", rated);
    }

    public String getRated() {
        return get("rated");
    }

    public void setAmount(java.math.BigDecimal amount) {
        set("amount", amount);
    }

    public java.math.BigDecimal getAmount() {
        return get("amount");
    }

}
