package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

import java.math.BigDecimal;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMallSku<M extends BaseMallSku<M>> extends BaseModel<M> implements IBean {
    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return get("id");
    }

    public void setSkuName(java.lang.String skuName) {
        set("skuName", skuName);
    }

    public java.lang.String getSkuName() {
        return get("skuName");
    }

    public void setSku(java.lang.String sku) {
        set("sku", sku);
    }

    public java.lang.String getSku() {
        return get("sku");
    }

    public void setCategory(java.lang.String category) {
        set("category", category);
    }

    public java.lang.String getCategory() {
        return get("category");
    }

    public void setAttribute(java.lang.String attribute) {
        set("attribute", attribute);
    }

    public java.lang.String getAttribute() {
        return get("attribute");
    }

    public void setStatus(java.lang.Integer status) {
        set("status", status);
    }

    public java.lang.Integer getStatus() {
        return get("status");
    }

    public void setSpecName(java.lang.String specName) {
        set("specName", specName);
    }

    public java.lang.String getSpecName() {
        return get("specName");
    }

    public void setRemark(java.lang.String remark) {
        set("remark", remark);
    }

    public java.lang.String getRemark() {
        return get("remark");
    }

    public void setCateName(String cateName) {
        set("cateName", cateName);
    }

    public String getCateName() {
        return get("cateName");
    }

    /**
     * 拓展mall_sku_price表字段price
     * @param price
     */
    public void setPrice(BigDecimal price) {
        set("price", price);
    }

    /**
     * 拓展mall_sku_price表字段price
     * @return
     */
    public BigDecimal getPrice() {
        return get("price");
    }
}
