package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAsAftersaleod<M extends BaseAsAftersaleod<M>> extends BaseModel<M> implements IBean {

	public void setAsodID(String asodID) {
		set("asodID", asodID);
	}

	public String getAsodID() {
		return get("asodID");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}

	public String getCustomer() {
		return get("customer");
	}

	public void setExecuter(String executer) {
		set("executer", executer);
	}

	public String getExecuter() {
		return get("executer");
	}

	public void setExpress(String express) {
		set("express", express);
	}

	public String getExpress() {
		return get("express");
	}

	public void setCourierNum(String courierNum) {
		set("courierNum", courierNum);
	}

	public String getCourierNum() {
		return get("courierNum");
	}

	public void setBkexpress(String bkexpress) {
		set("bkexpress", bkexpress);
	}

	public String getBkexpress() {
		return get("bkexpress");
	}

	public void setBkcourierNum(String bkcourierNum) {
		set("bkcourierNum", bkcourierNum);
	}

	public String getBkcourierNum() {
		return get("bkcourierNum");
	}

	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}

	public java.math.BigDecimal getAmount() {
		return get("amount");
	}

	public void setAddr(String addr) {
		set("addr", addr);
	}

	public String getAddr() {
		return get("addr");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setCusName(String cusName) {
		set("cusName", cusName);
	}

	public String getCusName() {
		return get("cusName");
	}

}
