package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSkStockLog<M extends BaseSkStockLog<M>> extends BaseModel<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}

	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setSku(String sku) {
		set("sku", sku);
	}

	public String getSku() {
		return get("sku");
	}

	public void setModule(String module) {
		set("module", module);
	}

	public String getModule() {
		return get("module");
	}

	public void setSourceCode(String sourceCode) {
		set("sourceCode", sourceCode);
	}

	public String getSourceCode() {
		return get("sourceCode");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setOldQuantity(Integer oldQuantity) {
		set("oldQuantity", oldQuantity);
	}

	public Integer getOldQuantity() {
		return get("oldQuantity");
	}

}
