package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSkuOutbound<M extends BaseSkuOutbound<M>> extends BaseModel<M> implements IBean {

	public void setOutboundID(String outboundID) {
		set("outboundID", outboundID);
	}

	public String getOutboundID() {
		return get("outboundID");
	}

	public void setExecutor(String executor) {
		set("executor", executor);
	}

	public String getExecutor() {
		return get("executor");
	}

	public void setExtime(java.util.Date extime) {
		set("extime", extime);
	}

	public java.util.Date getExtime() {
		return get("extime");
	}

}
