package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAsAftersaleodDe<M extends BaseAsAftersaleodDe<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setAsodID(String asodID) {
		set("asodID", asodID);
	}

	public String getAsodID() {
		return get("asodID");
	}

	public void setSku(String sku) {
		set("sku", sku);
	}

	public String getSku() {
		return get("sku");
	}

	public void setQuantity(Integer quantity) {
		set("quantity", quantity);
	}

	public Integer getQuantity() {
		return get("quantity");
	}

	public void setNewqty(Integer newqty) {
		set("newqty", newqty);
	}

	public Integer getNewqty() {
		return get("newqty");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

}
