package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCustomerUpRated<M extends BaseCustomerUpRated<M>> extends BaseModel<M> implements IBean {

	public void setCustomer(String customer) {
		set("customer", customer);
	}

	public String getCustomer() {
		return get("customer");
	}

	public void setUp(String up) {
		set("up", up);
	}

	public String getUp() {
		return get("up");
	}

	public void setSku(String sku) {
		set("sku", sku);
	}

	public String getSku() {
		return get("sku");
	}

	public void setRated(java.math.BigDecimal rated) {
		set("rated", rated);
	}

	public java.math.BigDecimal getRated() {
		return get("rated");
	}

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

}
