package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConsoleSequence<M extends BaseConsoleSequence<M>> extends BaseModel<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setCode(Integer code) {
		set("code", code);
	}

	public Integer getCode() {
		return get("code");
	}

}
