package com.fruit.model.base;

import com.fruit.core.model.BaseModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMallCustomerShop<M extends BaseMallCustomerShop<M>> extends BaseModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}

	public Long getId() {
		return get("id");
	}

	public void setCustomer(String customer) {
		set("customer", customer);
	}

	public String getCustomer() {
		return get("customer");
	}

	public void setCategory(String category) {
		set("category", category);
	}

	public String getCategory() {
		return get("category");
	}

	public void setShopName(String shopName) {
		set("shopName", shopName);
	}

	public String getShopName() {
		return get("shopName");
	}

	public void setShopAddr(String shopAddr) {
		set("shopAddr", shopAddr);
	}

	public String getShopAddr() {
		return get("shopAddr");
	}

	public void setShopPic(String shopPic) {
		set("shopPic", shopPic);
	}

	public String getShopPic() {
		return get("shopPic");
	}

}
